[phases.setup]
aptPkgs = [
    "python3-dev",
    "libjpeg-dev",
    "zlib1g-dev",
    "libpng-dev",
    "libfreetype6-dev",
    "liblcms2-dev",
    "libwebp-dev",
    "tcl8.6-dev",
    "tk8.6-dev",
    "python3-tk",
    "libharfbuzz-dev",
    "libfribidi-dev",
    "libxcb1-dev"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
